-- Insert checklist definitions
INSERT INTO public.checklist_definitions (checklist_type, item_order, label) VALUES
('QLF', 1, 'Acesso livre ao quadro'),
('QLF', 2, 'Aterramento das portas'),
('QLF', 3, 'DPS'),
('QLF', 4, 'Identificação do quadro'),
('QLF', 5, 'Identificação de tensão'),
('QLF', 6, 'Padrão de cores, barramento, terra e neutro'),
('QLF', 7, 'Isolações bem feitas e fiação aparente'),
('QLF', 8, 'Identificação de circuitos com anilhas'),
('QLF', 9, 'Identificação dos disjuntores e circuitos'),
('QLF', 10, 'Folha de circuitos'),
('QLF', 11, 'Painel bem fixo e sem buracos'),
('QLF', 12, 'Disjuntor de iluminação de emergência identificado'),
('QLF', 13, 'Fechadura e miolo das portas'),
('QLF', 14, 'Adesivo PERIGO CHOQUE ELÉTRICO'),
('QLF', 15, 'Limpeza do quadro'),
('QLF', 16, 'Projeto aprovado na porta do painel'),
('QLF', 17, 'LEDs do painel'),
('QLF', 18, 'Borracha de vedação'),
('QLF', 19, 'Pintura'),
('QLF', 20, 'Porta documentos'),
('CM', 1, 'Acesso livre ao quadro'),
('CM', 2, 'Aterramento das portas'),
('CM', 3, 'Identificação do quadro'),
('CM', 4, 'Identificação de tensão'),
('CM', 5, 'Isolações bem feitas e fiação aparente'),
('CM', 6, 'Painel bem fixo e sem buracos'),
('CM', 7, 'Fechadura e miolo das portas'),
('CM', 8, 'Adesivo PERIGO CHOQUE ELÉTRICO'),
('CM', 9, 'Limpeza do quadro'),
('CM', 10, 'Projeto aprovado na porta do painel'),
('CM', 11, 'Medidor de tensão'),
('CM', 12, 'Borracha de vedação'),
('CM', 13, 'Pintura'),
('CM', 14, 'Vidros'),
('CM', 15, 'Porta documentos'),
('QE-AC', 1, 'Acesso livre ao quadro'),
('QE-AC', 2, 'Aterramento das portas'),
('QE-AC', 3, 'Identificação do quadro'),
('QE-AC', 4, 'Identificação de tensão'),
('QE-AC', 5, 'Isolações bem feitas e fiação aparente'),
('QE-AC', 6, 'Painel bem fixo e sem buracos'),
('QE-AC', 7, 'Fechadura e miolo das portas'),
('QE-AC', 8, 'Adesivo PERIGO CHOQUE ELÉTRICO'),
('QE-AC', 9, 'Limpeza do quadro'),
('QE-AC', 10, 'Projeto aprovado na porta do painel'),
('QE-AC', 11, 'Borracha de vedação'),
('QE-AC', 12, 'Pintura'),
('QE-AC', 13, 'Porta documentos'),
('CT', 1, 'Acesso livre ao quadro'),
('CT', 2, 'Aterramento das portas'),
('CT', 3, 'Identificação do quadro'),
('CT', 4, 'Identificação de tensão'),
('CT', 5, 'Painel bem fixo e sem buracos'),
('CT', 6, 'Fechadura e miolo das portas'),
('CT', 7, 'Adesivo PERIGO CHOQUE ELÉTRICO'),
('CT', 8, 'Limpeza do quadro'),
('CT', 9, 'Projeto aprovado na porta do painel'),
('CT', 10, 'Borracha de vedação'),
('CT', 11, 'Pintura'),
('CT', 12, 'Porta documentos');

-- Insert boards (131 boards)
INSERT INTO public.boards (code, location, type, checklist_type, description, status) VALUES
('QLF-1A', 'GT 01', 'QLF', 'QLF', '', 'Pendente'),
('CM1.1', 'GT 01', 'CM', 'CM', '', 'Pendente'),
('QE-AC-04', 'GT 01', 'QE-AC', 'QE-AC', '', 'Pendente'),
('QLF-1C', 'GT 02', 'QLF', 'QLF', '', 'Pendente'),
('CM1.3', 'GT 02', 'CM', 'CM', '', 'Pendente'),
('CD CHUVEIRO', 'GT 02', 'CD', 'QE-AC', '', 'Pendente'),
('QLF-1B', 'GT 02', 'QLF', 'QLF', '', 'Pendente'),
('QLF-EXT-01', 'GT 02', 'QLF', 'QLF', '', 'Pendente'),
('CM1.4', 'GT 02', 'CM', 'CM', '', 'Pendente'),
('QE-AC CM06', 'GT 02', 'QE-AC', 'QE-AC', '', 'Pendente'),
('QLF-1D', 'GT 02', 'QLF', 'QLF', '', 'Pendente'),
('CM12 VESTIÁRIO MASC DOCA 2', 'GT 02', 'CM', 'CM', '', 'Pendente'),
('QLF-2A', 'GT 03', 'QLF', 'QLF', '', 'Pendente'),
('QE-AC-19', 'GT 03', 'QE-AC', 'QE-AC', '', 'Pendente'),
('CM2.1', 'GT 03', 'CM', 'CM', '', 'Pendente'),
('QLF-2B', 'GT 03', 'QLF', 'QLF', '', 'Pendente'),
('CM 2.2', 'GT 04', 'CM', 'CM', '', 'Pendente'),
('QLF-PONTO DE COBRANÇA', 'GT 04', 'QLF', 'QLF', '', 'Pendente'),
('QLF-2C', 'GT 05', 'QLF', 'QLF', '', 'Pendente'),
('QE-AC-14', 'GT 05', 'QE-AC', 'QE-AC', '', 'Pendente'),
('CM03', 'GT 05', 'CM', 'CM', '', 'Pendente'),
('CM2.3', 'GT 05', 'CM', 'CM', '', 'Pendente'),
('QLF-2D', 'GT 05', 'QLF', 'QLF', '', 'Pendente'),
('CM3.4', 'GT 06', 'CM', 'CM', '', 'Pendente'),
('CM3.9', 'GT 06', 'CM', 'CM', '', 'Pendente'),
('CM3.8', 'GT 07', 'CM', 'CM', '', 'Pendente'),
('QE-AC-03', 'GT 07', 'QE-AC', 'QE-AC', '', 'Pendente'),
('CM20', 'GT 07', 'CM', 'CM', '', 'Pendente'),
('QE-AC-02', 'GT 07', 'QE-AC', 'QE-AC', '', 'Pendente'),
('QE-AC-01', 'GT 07', 'QE-AC', 'QE-AC', '', 'Pendente'),
('QLF-1E', 'GT 07', 'QLF', 'QLF', '', 'Pendente'),
('QLF-3C', 'GT 07', 'QLF', 'QLF', '', 'Pendente'),
('QE-AC-21', 'GT 07', 'QE-AC', 'QE-AC', '', 'Pendente'),
('QLF-LOJAS ESCADAS ROLANTES AC', 'GT 07', 'QLF', 'QLF', '', 'Pendente'),
('QLF-3A', 'GT 07', 'QLF', 'QLF', '', 'Pendente'),
('QE-AC-16', 'GT 07', 'QE-AC', 'QE-AC', '', 'Pendente'),
('CM04', 'GT 07', 'CM', 'CM', '', 'Pendente'),
('QLF-3B', 'GT 07', 'QLF', 'QLF', '', 'Pendente'),
('CM3.3', 'GT 07', 'CM', 'CM', '', 'Pendente'),
('CM3.1', 'GT 07', 'CM', 'CM', '', 'Pendente'),
('CM3.2', 'GT 08', 'CM', 'CM', '', 'Pendente'),
('QLF-3D', 'GT 08', 'QLF', 'QLF', '', 'Pendente'),
('QE-AC-20', 'GT 09', 'QE-AC', 'QE-AC', '', 'Pendente'),
('CM4.2', 'GT 09', 'CM', 'CM', '', 'Pendente'),
('QLF-CALÇADÃO', 'GT 09', 'QLF', 'QLF', '', 'Pendente'),
('QLF-2E', 'GT 09', 'QLF', 'QLF', '', 'Pendente'),
('CM4.3', 'GT 09', 'CM', 'CM', '', 'Pendente'),
('QLF-E-B-LIMPEZA', 'GT 09', 'QLF', 'QLF', '', 'Pendente'),
('QLF-B.HIDRANTE', 'GT 09', 'QLF', 'QLF', '', 'Pendente'),
('QE-AC-17 SISTERNA', 'GT 09', 'QE-AC', 'QE-AC', '', 'Pendente'),
('QE-AC-12', 'GT 11', 'QE-AC', 'QE-AC', '', 'Pendente'),
('CM4.1', 'GT 11', 'CM', 'CM', '', 'Pendente'),
('CM5.1', 'GT 11', 'CM', 'CM', '', 'Pendente'),
('QLF-5B', 'GT 12', 'QLF', 'QLF', '', 'Pendente'),
('QLF-5A', 'GT 12', 'QLF', 'QLF', '', 'Pendente'),
('QE-AC-05 VENTILAÇÃO 14', 'GT 12', 'QE-AC', 'QE-AC', '', 'Pendente'),
('QE-AC-03', 'GT 12', 'QE-AC', 'QE-AC', '', 'Pendente'),
('CM5.2', 'GT 12', 'CM', 'CM', '', 'Pendente'),
('QLF-1B', 'GT 13', 'QLF', 'QLF', '', 'Pendente'),
('CM1.5', 'GT 13', 'CM', 'CM', '', 'Pendente'),
('QE-AC-29', 'GT 13', 'QE-AC', 'QE-AC', '', 'Pendente'),
('QLF-1C', 'GT 14', 'QLF', 'QLF', '', 'Pendente'),
('CM1.6', 'GT 14', 'CM', 'CM', '', 'Pendente'),
('CM1.7', 'GT 15', 'CM', 'CM', '', 'Pendente'),
('CM1.8', 'GT 15', 'CM', 'CM', '', 'Pendente'),
('QLF-1E', 'GT 16', 'QLF', 'QLF', '', 'Pendente'),
('QE-AC-23', 'GT 16', 'QE-AC', 'QE-AC', '', 'Pendente'),
('QLF-N/E COZINHA', 'GT 16', 'QLF', 'QLF', '', 'Pendente'),
('QLF-2C', 'GT 17', 'QLF', 'QLF', '', 'Pendente'),
('CM2.5', 'GT 17', 'CM', 'CM', '', 'Pendente'),
('QLF-2B', 'GT 17', 'QLF', 'QLF', '', 'Pendente'),
('CM2.4', 'GT 17', 'CM', 'CM', '', 'Pendente'),
('QLF-2A', 'GT 17', 'QLF', 'QLF', '', 'Pendente'),
('CM2.6', 'GT 18', 'CM', 'CM', '', 'Pendente'),
('QE-AC-24', 'GT 18', 'QE-AC', 'QE-AC', '', 'Pendente'),
('QLF-3B', 'GT 19', 'QLF', 'QLF', '', 'Pendente'),
('QLF-EXT.04', 'GT 19', 'QLF', 'QLF', '', 'Pendente'),
('QE-AC-34', 'GT 19', 'QE-AC', 'QE-AC', '', 'Pendente'),
('CM3.7', 'GT 19', 'CM', 'CM', '', 'Pendente'),
('QLF-3C', 'GT 20', 'QLF', 'QLF', '', 'Pendente'),
('CM3.6', 'GT 20', 'CM', 'CM', '', 'Pendente'),
('CD DOCA 5', 'GT 20', 'CD', 'QE-AC', '', 'Pendente'),
('QE-AC-26 REFEITÓRIO', 'GT 20', 'QE-AC', 'QE-AC', '', 'Pendente'),
('CM3.5', 'GT 20', 'CM', 'CM', '', 'Pendente'),
('QLF-3A', 'GT 20', 'QLF', 'QLF', '', 'Pendente'),
('QE-AC-25', 'GT 20', 'QE-AC', 'QE-AC', '', 'Pendente'),
('CM09', 'GT 20', 'CM', 'CM', '', 'Pendente'),
('QLF-5A', 'GT 21', 'QLF', 'QLF', '', 'Pendente'),
('CM4.5', 'GT 21', 'CM', 'CM', '', 'Pendente'),
('CM5.7', 'GT 22', 'CM', 'CM', '', 'Pendente'),
('CM5.4', 'GT 22', 'CM', 'CM', '', 'Pendente'),
('QE-AC-33', 'GT 22', 'QE-AC', 'QE-AC', '', 'Pendente'),
('QLF-EXT.03', 'GT 22', 'QLF', 'QLF', '', 'Pendente'),
('QLF-AUX 03', 'GT 22', 'QLF', 'QLF', '', 'Pendente'),
('CM5.5', 'GT 22', 'CM', 'CM', '', 'Pendente'),
('QLF-5B', 'GT 22', 'QLF', 'QLF', '', 'Pendente'),
('CM5.6', 'GT 23', 'CM', 'CM', '', 'Pendente'),
('QE-AC-32', 'GT 23', 'QE-AC', 'QE-AC', '', 'Pendente'),
('QLF-5C', 'GT 23', 'QLF', 'QLF', '', 'Pendente'),
('CM5.3', 'GT 24', 'CM', 'CM', '', 'Pendente'),
('QE-QC-08', 'GT 24', 'QE-AC', 'QE-AC', '', 'Pendente'),
('CM4.4', 'BAIXO BARRA', 'CM', 'CM', '', 'Pendente'),
('QLF-4B', 'BAIXO BARRA', 'QLF', 'QLF', '', 'Pendente'),
('QE-AC-11', 'CORREDOR MANUTENÇÃO', 'QE-AC', 'QE-AC', '', 'Pendente'),
('QE-AC-19', 'CORREDOR MANUTENÇÃO', 'QE-AC', 'QE-AC', '', 'Pendente'),
('QE-CAG CORREDOR DOCA 3 CAG', 'SEM GT', 'QE-CAG', 'QE-AC', '', 'Pendente'),
('QF-B-SPRINKLER CAG', 'SEM GT', 'QF', 'QE-AC', '', 'Pendente'),
('QF-BOMBAS REUSO', 'SEM GT', 'QF', 'QE-AC', '', 'Pendente'),
('QF-DG', 'SEM GT', 'QF', 'QE-AC', '', 'Pendente'),
('QLF-1B TELECOM DG', 'SEM GT', 'QLF', 'QLF', '', 'Pendente'),
('QE-AC-06', 'SUB2', 'QE-AC', 'QE-AC', '', 'Pendente'),
('QLF-2F', 'SUB2', 'QLF', 'QLF', '', 'Pendente'),
('QLF-EXT02', 'SUB2', 'QLF', 'QLF', '', 'Pendente'),
('QLF-AUX-EXT.02', 'SUB2', 'QLF', 'QLF', '', 'Pendente'),
('QCR-GG2', 'SUB2', 'QCR', 'QE-AC', '', 'Pendente'),
('QRC-GG1', 'SUB1', 'QRC', 'QE-AC', '', 'Pendente'),
('QE-AC-28', 'GT18', 'QE-AC', 'QE-AC', '', 'Pendente'),
('QE-AC-27', 'QTO FEMININO CORREDOR ADM', 'QE-AC', 'QE-AC', '', 'Pendente'),
('QE-AC-10', 'QTO MASCULINO CORREDOR MANUTENÇÃO', 'QE-AC', 'QE-AC', '', 'Pendente'),
('QE-AC-02', 'QTO MASCULINO PRAÇA', 'QE-AC', 'QE-AC', '', 'Pendente'),
('QE-AC-13', 'QTO RENNER JÓCKEY', 'QE-AC', 'QE-AC', '', 'Pendente'),
('QF-E-ELEVADOR-03', '', 'QF', 'QE-AC', '', 'Pendente'),
('QF-E-ELEVADOR-04', '', 'QF', 'QE-AC', '', 'Pendente'),
('QF-E-DAFE-04', '', 'QF', 'QE-AC', '', 'Pendente'),
('QLC-E ELEVADOR 03/04', '', 'QLC', 'QE-AC', '', 'Pendente'),
('QF-E ELEVADOR-01', '', 'QF', 'QE-AC', '', 'Pendente'),
('QF-E-ELEVADOR 02', '', 'QF', 'QE-AC', '', 'Pendente'),
('QF-E DAFE 02', '', 'QF', 'QE-AC', '', 'Pendente'),
('QLC-E ELEVADOR 01/02', '', 'QLC', 'QE-AC', '', 'Pendente'),
('CM4.6', 'TELHADO', 'CM', 'CM', '', 'Pendente'),
('CASA DE MÁQUINA ELEVADOR COBASE', 'TELHADO', 'Outros', 'QE-AC', '', 'Pendente');